name: Waka Readme

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LOC_CHART: "False"
          UPDATED_DATE_FORMAT: "%m/%d/%Y %H:%M:%S"
          COMMIT_BY_ME: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "False"
